// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Server.Database;

#nullable disable

namespace WebApp.Server.Migrations
{
    [DbContext(typeof(ScoreCasterDbContext))]
    partial class ScoreCasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Core.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinResponseLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MinResponseLength = 0,
                            Text = "Question 0 from EF"
                        },
                        new
                        {
                            ID = 2,
                            MinResponseLength = 0,
                            Text = "Question 1 from EF"
                        },
                        new
                        {
                            ID = 3,
                            MinResponseLength = 0,
                            Text = "Question 2 from EF"
                        });
                });

            modelBuilder.Entity("Core.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUserID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsefulnessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionID");

                    b.HasIndex("UsefulnessId");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("Core.Response", b =>
                {
                    b.HasOne("Core.Question", null)
                        .WithMany("Responses")
                        .HasForeignKey("QuestionID");

                    b.HasOne("Core.Response", "Usefulness")
                        .WithMany()
                        .HasForeignKey("UsefulnessId");

                    b.Navigation("Usefulness");
                });

            modelBuilder.Entity("Core.Question", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
